SELECT
    A.ANIMAL_ID,
    A.NAME
FROM (
    SELECT
        O.ANIMAL_ID,
        O.NAME,
        ROW_NUMBER() OVER (ORDER BY (O.DATETIME - I.DATETIME) DESC) AS ROWNUM
    FROM ANIMAL_INS I
    INNER JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
) A
WHERE A.ROWNUM <= 2
ORDER BY A.ROWNUM;
