-- 코드를 입력하세요
SELECT C1.CAR_ID, C1.CAR_TYPE, C1.DAILY_FEE * 30 * (1-C3.DISCOUNT_RATE*0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C1 
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C3
ON C1.CAR_TYPE = C3.CAR_TYPE
AND TO_NUMBER(RTRIM(C3.DURATION_TYPE, '일 이상')) = 30
WHERE C1.CAR_TYPE IN ('세단', 'SUV')
AND C1.CAR_ID NOT IN (
                        SELECT DISTINCT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE TO_DATE('20221101', 'YYYY-MM-DD') BETWEEN START_DATE 
                        AND END_DATE
                        OR TO_DATE('20221130', 'YYYY-MM-DD') BETWEEN START_DATE 
                        AND END_DATE
                    )
AND C1.DAILY_FEE * 30 * (1-C3.DISCOUNT_RATE*0.01) >= 500000 
AND C1.DAILY_FEE * 30 * (1-C3.DISCOUNT_RATE*0.01) < 2000000
ORDER BY 3 DESC, 2, 1 DESC;