-- 코드를 작성해주세요
WITH RECURSIVE RS AS (
    SELECT
        ID
        , PARENT_ID
        , 1 GENERATION
    FROM ECOLI_DATA A 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        D.ID
        , D.PARENT_ID
        , R.GENERATION + 1 
    FROM RS R
    INNER JOIN ECOLI_DATA D
    ON R.ID = D.PARENT_ID
)

SELECT
    COUNT(R1.ID) COUNT
    , R1.GENERATION
FROM RS R1
LEFT OUTER JOIN RS R2
ON R1.ID = R2.PARENT_ID
WHERE R2.ID IS NULL
GROUP BY R1.GENERATION
ORDER BY 2
;

-- 조회용 쿼리
# SELECT
#     A.ID
#     , A.PARENT_ID
#     , B.ID
#     , B.PARENT_ID
# FROM ECOLI_DATA A
# LEFT OUTER JOIN ECOLI_DATA B
# ON A.ID = B.PARENT_ID