-- 코드를 입력하세요
SELECT C.CAR_ID, MAX(C.AVAILABLITY)
FROM  (
    SELECT CAR_ID
            , CASE WHEN TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221016' AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221016' THEN '대여중'
            ELSE '대여 가능'
            END AS AVAILABLITY
            , START_DATE
            , END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) C
GROUP BY C.CAR_ID
ORDER BY 1 DESC;