-- 코드를 입력하세요
SELECT M.MEMBER_ID, M.MEMBER_NAME, M.GENDER, DATE_FORMAT(M.DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE M
WHERE DATE_FORMAT(M.DATE_OF_BIRTH, '%m') = '03' 
AND M.GENDER = 'W'AND M.TLNO IS NOT NULL
ORDER BY MEMBER_ID;