-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) "HOUR", COUNT(*) "COUNT"
FROM ANIMAL_OUTS A
WHERE TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) BETWEEN 9 AND 19
GROUP BY TO_CHAR(A.DATETIME, 'HH24')
ORDER BY 1;