-- 코드를 작성해주세요
SELECT
    CHILD.ID ID
    , CHILD.GENOTYPE GENOTYPE
    , PARENT.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA PARENT
LEFT OUTER JOIN ECOLI_DATA CHILD
ON PARENT.ID = CHILD.PARENT_ID
WHERE PARENT.GENOTYPE & CHILD.GENOTYPE = PARENT.GENOTYPE
ORDER BY 1;