SELECT EXTRACT(MONTH FROM C.START_DATE) "MONTH", C.CAR_ID,
COUNT(*) "RECORDS"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
WHERE C.CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD') 
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
AND C.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD') 
GROUP BY EXTRACT(MONTH FROM C.START_DATE), C.CAR_ID
HAVING COUNT(*) > 0
ORDER BY 1, 2 DESC;